# These are supported funding model platforms

github: Ruben-Arushanyan # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: rubenarushanyan # Replace with a single Patreon username
open_collective: ruben-arushanyan # Replace with a single Open Collective username
ko_fi: rubenarushanyan # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: rubenarushanyan # Replace with a single Liberapay username
issuehunt: ruben-arushanyan # Replace with a single IssueHunt username
otechie: rubenarushanyan # Replace with a single Otechie username
custom: ["https://www.paypal.me/rubenarushanyan"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
